#proxy:
#  secretToken: "57856fad13702360592b9a1a97d1924c406f465390615934957d05422bc7d24a"
#  https:
#    enabled: false

hub:
#  config:
#    Authenticator:
#      admin_users:
#        - akhtyamovpavel
#        - akhtyamovpavel@gmail.com
#      allow_all: true
#    GitLabOAuthenticator:
#      client_id: "35189e308948d4f04c3f68864bea0c97fb5d7d7bc49753c00f7c0f77b0c05527"
#      client_secret: "gloas-d3e711de9c6b9ee2e79e633b17b8951df32ee3317aab3bc3dc651e16d9fe648e"
#      oauth_callback_url: "https://jupyterhub.sunpixel.ru/hub/oauth_callback"
#      scope:
#        - read_user
#        - read_api
#        - openid
#    JupyterHub:
#      authenticator_class: gitlab
#  extraEnv:
#    GITLAB_HOST: "gitlab.akhcheck.ru"
  extraConfig:
    ngshare.py: |
      c.JupyterHub.services.append({
        'name': 'ngshare',
        'url': 'http://ngshare:8080',
        'api_token': 'demo_token_9wRp0h4BLzAnC88jjBfpH0fa4QV9tZNI',
        'oauth_no_confirm': True})

singleuser:
  image:
    name: ngshare-singleuser-sample
    tag: 0.0.1
  memory:
    limit: 2G
    guarantee: 500M
  networkPolicy:
    egressAllowRules:
     privateIPs: true
